# Change baseurl before deploy
baseurl = "https://newborn22.github.io"
languageCode = "en-us"
paginate = 5
title = "newborn22 blog"

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# mutilingual
# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

defaultContentLanguageInSubdir = true

[languages]
[languages.zh-cn]
contentDir = 'content/zh'
disabled = false
languageCode = 'zh-cn'
languageDirection = 'ltr'
languageName = '简体中文'
title = 'newborn22'
weight = 1
[languages.zh-cn.params]
[languages.zh-cn.params.sidebar]
emoji = "❤️"
subtitle = "欢迎光临"

[languages.en]
contentDir = 'content/en'
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'newborn22'
weight = 2
[languages.en.params]
[languages.en.params.sidebar]
emoji = "☀️"
subtitle = "hi there~"